import { afterEach, describe, expect, it, vi } from 'vitest';
import { classify, privateAddress, probe, sanitizeSettings, skipReason } from '../src/checker';
import { DEFAULT_SETTINGS } from '../src/types';
afterEach(() => { vi.unstubAllGlobals(); });
describe('network policy and diagnostics', () => {
  it.each(['127.0.0.1','10.1.2.3','172.16.0.1','192.168.1.1','169.254.169.254','100.64.0.1','[::1]','[fc00::1]','[fe80::1]','[::ffff:7f00:1]','nas','a.local','a.home.arpa'])('skips private destination %s', h => expect(privateAddress(h)).toBe(true));
  it.each(['8.8.8.8','172.15.1.1','example.com','[2606:4700:4700::1111]'])('allows public destination %s', h => expect(privateAddress(h)).toBe(false));
  it('skips non HTTP and URL credentials', () => { expect(skipReason('chrome://settings/', true)).toContain('非 HTTP'); expect(skipReason('https://user:pass@example.com', true)).toContain('凭据'); expect(skipReason('http://2130706433', false)).toContain('内网'); });
  it.each([[200,'ok'],[204,'ok'],[404,'http-error'],[410,'http-error'],[503,'http-error'],[401,'restricted'],[403,'restricted'],[429,'restricted'],[302,'unknown']] as const)('classifies %s', (n, status) => expect(classify(n)).toBe(status));
  it('rechecks HEAD 405 using bounded GET without credentials', async () => { const calls: RequestInit[] = []; vi.stubGlobal('fetch', async (_url: string, init: RequestInit) => { calls.push(init); return new Response(init.method === 'GET' ? new ReadableStream({ type: 'bytes', start(controller) { controller.enqueue(new Uint8Array(100000)); controller.close(); } }) : null, { status: init.method === 'HEAD' ? 405 : 200 }); }); const result = await probe('https://example.com', DEFAULT_SETTINGS); expect(result.status).toBe('ok'); expect(result.bytesRead).toBe(65536); expect(calls.map(c => c.method)).toEqual(['HEAD','GET']); expect(calls.every(c => c.credentials === 'omit' && c.referrerPolicy === 'no-referrer')).toBe(true); expect(calls[1].headers).toEqual({ Range: 'bytes=0-65535' }); });
  it('retains unknown classification when detailed errors are absent', async () => { vi.stubGlobal('fetch', () => Promise.reject(new Error('Failed to fetch'))); const result = await probe('https://example.com', DEFAULT_SETTINGS); expect(result.status).toBe('unknown'); expect(result.rawError).toBeUndefined(); expect(result.reason).toContain('未提供详细错误'); });
  it('reports timeout as unknown and cancellation as skipped', async () => { vi.stubGlobal('fetch', (_url: string, init: RequestInit) => new Promise((_resolve, reject) => { if (init.signal?.aborted) reject(new Error('aborted')); else init.signal?.addEventListener('abort', () => reject(new Error('aborted'))); })); const timeout = await probe('https://example.com', { ...DEFAULT_SETTINGS, timeoutMs: 10 }); expect(timeout.status).toBe('unknown'); const c = new AbortController(); c.abort(); const cancelled = await probe('https://example.com', DEFAULT_SETTINGS, undefined, c.signal); expect(cancelled.reason).toBe('用户取消'); });
  it('clamps persisted settings to bounded concurrency and timeout', () => expect(sanitizeSettings({ allowPrivate: false, concurrency: 99, perHost: 99, timeoutMs: 90000 })).toEqual({ allowPrivate: false, concurrency: 12, perHost: 2, timeoutMs: 12000 }));
});
