import { describe, expect, it } from 'vitest';
import { JSDOM } from 'jsdom';
import { decodeBackup, encodeBackup, exportHtml, importStats, parseFile, parseHtml, sha256 } from '../src/formats';
import { duplicates, flatten, renamePreview } from '../src/tree';
import { DEFAULT_SETTINGS, type BackupData } from '../src/types';
import { MockBookmarks } from './mock-browser';
globalThis.DOMParser = new JSDOM().window.DOMParser;
const bytes = (s: string) => new TextEncoder().encode(s);
describe('format preservation', () => {
  it('imports nested HTML, Chinese, special characters and empty folders', () => { const nodes = parseHtml('<!DOCTYPE NETSCAPE-Bookmark-file-1><DL><p><DT><H3 ADD_DATE="123">工作 &amp; 收藏</H3><DL><p><DT><A HREF="https://example.com/?a=1&amp;b=2#中" TAGS="研究,设计" ICON="data:abc">中文 &lt;指南&gt;</A><DT><H3>空目录</H3><DL><p></DL><p></DL><p></DL><p>'); expect(importStats(nodes)).toEqual({ bookmarks: 1, folders: 2 }); expect(nodes[0].children?.[0].url).toBe('https://example.com/?a=1&b=2#中'); expect(nodes[0].children?.[0].raw).toMatchObject({ attributes: { tags: '研究,设计', icon: 'data:abc' } }); });
  it('keeps raw Chromium JSON bytes, unknown fields, large numeric lexemes', async () => { const input = '{"roots":{"bookmark_bar":{"name":"中文","type":"folder","children":[{"type":"url","name":"A","url":"https://a.test","mystery":9007199254740993123}]}}}'; const p = await parseFile('Bookmarks', bytes(input)); expect(p.source.bytes).toEqual(Array.from(bytes(input))); expect(p.nodes[0].children?.[0].raw).toContain('9007199254740993123'); expect(p.source.sha256).toBe(await sha256(bytes(input))); });
  it('imports Firefox JSON and retains separator and annotation bytes in original', async () => { const p = await parseFile('firefox.json', bytes('{"type":"text/x-moz-place-container","children":[{"type":"text/x-moz-place-container","title":"空","children":[]},{"type":"text/x-moz-place","uri":"https://a.test/","title":"中","annos":[{"name":"x","value":9}]},{"type":"text/x-moz-place-separator"}]}')); expect(importStats(p.nodes)).toEqual({ bookmarks: 1, folders: 1 }); expect(p.nodes[1].raw).toContain('annos'); });
  it('exports valid HTML round trips while excluding trash', async () => { const api = new MockBookmarks(); const f = await api.create({ parentId: 'bar-local', title: '回收' }); await api.create({ parentId: f.id, title: 'secret', url: 'https://secret.test' }); await api.create({ parentId: 'bar-local', title: '中文 <>&"', url: 'https://example.com/?q=1&b=2' }); const html = exportHtml(await api.getTree(), [{ id: f.id, recycleRegion: 'bar-local' }]); expect(html).not.toContain('secret'); const imported = parseHtml(html); expect(importStats(imported).bookmarks).toBe(2); expect(JSON.stringify(imported)).toContain('中文 <>&'); });
  it('round trips full project ZIP originals, histories and snapshots', async () => { const api = new MockBookmarks(); const p = await parseFile('bookmarks.html', bytes('<DL><DT><A HREF="https://a.test">中文</A></DL>')); const data: BackupData = { format: 'bookmarker-project', version: 1, exportedAt: 1, profileId: 'foreign', tree: await api.getTree(), sources: [p.source], metadata: [], operations: [], snapshots: [], results: [], jobs: [], settings: DEFAULT_SETTINGS }; const packed = encodeBackup(data); const decoded = decodeBackup(packed); expect(decoded.sources[0]).toEqual(p.source); const preview = await parseFile('backup.zip', packed); expect(preview.warnings.join('')).toContain('不复用'); expect(preview.source.bytes).toEqual(Array.from(packed)); });
  it('exact URL duplicate matching preserves query, fragment and protocol', async () => { const api = new MockBookmarks(); for (const url of ['https://a.test/?q=1#x', 'https://a.test/?q=1#x', 'https://a.test/?q=2#x', 'http://a.test/?q=1#x', 'https://a.test/?q=1#y']) await api.create({ parentId: 'bar-local', url, title: 'a' }); const groups = duplicates(flatten(await api.getTree())); expect(groups.size).toBe(1); expect([...groups.values()][0]).toHaveLength(2); });
  it('previews literal replacement, affixes and numbering', async () => { const api = new MockBookmarks(); await api.create({ parentId: 'bar-local', title: 'A.$A', url: 'https://a.test' }); const nodes = flatten(await api.getTree()).filter(n => n.url && n.parentId === 'bar-local'); expect(renamePreview(nodes, { find: 'A', replace: 'B', prefix: '[', suffix: ']', numbering: true, start: 7 })[0].title).toBe('[7 B.$B]'); });
});
