import { useCallback, useDeferredValue, useEffect, useMemo, useRef, useState, type MouseEvent, type DragEvent } from 'react';
import { Bookmark, BookOpen, Search, Plus, Upload, Download, Folder, ChevronRight, ArrowUpDown, CheckCheck, Trash2, Copy, History, Settings2, PanelRightClose, PanelRightOpen, ArrowUpRight, RefreshCw, Pencil, FolderInput, X, ShieldCheck, CircleHelp, RotateCcw, Globe, Archive, HardDrive, Ellipsis, Link2, Check, LoaderCircle } from 'lucide-react';
import { isExtension, request } from '../client';
import { CHECK_PERMISSIONS } from '../checker';
import { descendants, duplicates, expected, flatten, hostname, renamePreview, type RenameRule } from '../tree';
import { encodeBackup, exportHtml, importStats, parseFile } from '../formats';
import { backupTransfer, importTransfer } from '../transfers';
import { DEFAULT_SETTINGS, STATUS_LABELS, type AppState, type BackupData, type BookmarkRecord, type CheckResult, type EditCommand, type OperationRecord, type ParsedImport, type Settings } from '../types';
import { Empty, FolderTree, formatTime, Modal, Notice, SafeOpen, Status, VirtualList } from './components';

type View = 'library' | 'duplicates' | 'trash' | 'history' | 'checks';
type Dialog = 'new-bookmark' | 'new-folder' | 'move' | 'rename' | 'import' | 'export' | 'settings' | 'check' | 'purge' | 'snapshot' | 'help' | null;
const initial: AppState = { tree: [], metadata: [], operations: [], snapshots: [], results: [], jobs: [], settings: DEFAULT_SETTINGS, profileId: '' };
const viewLabels: Record<View, string> = { library: '所有书签', duplicates: '重复书签', trash: '回收站', history: '操作与版本', checks: '链接检测' };
function download(bytes: Uint8Array | string, name: string, type: string) { const blob = new Blob([typeof bytes === 'string' ? bytes : new Uint8Array(bytes).buffer], { type }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }

export default function App() {
  const [state, setState] = useState(initial); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [view, setView] = useState<View>('library'); const [folderId, setFolderId] = useState<string>();
  const [query, setQuery] = useState(''); const search = useDeferredValue(query.trim().toLowerCase());
  const [scope, setScope] = useState('all'); const [typeFilter, setTypeFilter] = useState('all'); const [statusFilter, setStatusFilter] = useState('all'); const [domain, setDomain] = useState('');
  const [selected, setSelected] = useState<Set<string>>(new Set()); const anchor = useRef<string | undefined>(undefined);
  const [dialog, setDialog] = useState<Dialog>(null); const [showDetails, setShowDetails] = useState(true);
  const [error, setError] = useState(''); const [toast, setToast] = useState(''); const [context, setContext] = useState<{ x: number; y: number; node: BookmarkRecord }>();
  const dragging = useRef<string[]>([]); const loadTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const [parsed, setParsed] = useState<ParsedImport>(); const [targetId, setTargetId] = useState(''); const [draftTitle, setDraftTitle] = useState(''); const [draftUrl, setDraftUrl] = useState('');
  const [rename, setRename] = useState<RenameRule>({ find: '', replace: '', prefix: '', suffix: '', numbering: false, start: 1 });
  const [settings, setSettings] = useState<Settings>(DEFAULT_SETTINGS); const [checkScope, setCheckScope] = useState('selected');
  const [keepers, setKeepers] = useState<Record<string, string>>({}); const [purgeAck, setPurgeAck] = useState(false);

  const refresh = useCallback(async () => { if (!isExtension) { setLoading(false); return; } try { const next = await request<AppState>({ type: 'state' }); setState(next); } catch (e) { setError(String(e instanceof Error ? e.message : e)); } finally { setLoading(false); } }, []);
  useEffect(() => {
    void refresh(); if (!isExtension) return;
    void request({ type: 'resume' }).catch(e => setError(String(e)));
    const listener = (message: { type: string }) => { if (message.type === 'changed' && !loadTimer.current) loadTimer.current = setTimeout(() => { loadTimer.current = undefined; void refresh(); }, 250); };
    chrome.runtime.onMessage.addListener(listener); return () => { chrome.runtime.onMessage.removeListener(listener); clearTimeout(loadTimer.current); };
  }, [refresh]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 5500); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { if (!context) return; const close = () => setContext(undefined); window.addEventListener('click', close); return () => window.removeEventListener('click', close); }, [context]);
  const records = useMemo(() => flatten(state.tree, state.metadata), [state.tree, state.metadata]);
  const map = useMemo(() => new Map(records.map(n => [n.id, n])), [records]);
  const results = useMemo(() => { const m = new Map<string, CheckResult>(); for (const r of state.results) if ((m.get(r.nodeId)?.checkedAt ?? 0) <= r.checkedAt) m.set(r.nodeId, r); return m; }, [state.results]);
  const groups = useMemo(() => duplicates(records), [records]);
  const folder = folderId ? map.get(folderId) : undefined;
  const selectedNodes = records.filter(n => selected.has(n.id));
  const metadataMap = useMemo(() => new Map(state.metadata.map(m => [m.id, m])), [state.metadata]);
  const selectedDescendants = useMemo(() => {
    const ids = new Set<string>(); const queue = [...selected];
    while (queue.length) { const id = queue.pop()!; const n = map.get(id); if (!n || ids.has(id)) continue; ids.add(id); queue.push(...n.children); }
    return ids;
  }, [selected, map]);
  const mutable = selectedNodes.length > 0 && selectedNodes.every(n => !n.readOnly && !n.fixed && !metadataMap.get(n.id)?.recycleRegion);
  const folders = records.filter(n => n.url === undefined && n.parentId && !n.readOnly && !n.inTrash);
  const ordinary = records.filter(n => !n.inTrash && n.url !== undefined);
  const trashRoots = new Set(state.metadata.filter(m => m.recycleRegion).map(m => m.id));
  const deleted = records.filter(n => n.inTrash && n.parentId && trashRoots.has(n.parentId));
  const rows = useMemo(() => {
    const filterActive = !!search || !!domain || typeFilter !== 'all' || statusFilter !== 'all';
    const below = folderId ? descendants(folderId, records) : undefined;
    return records.filter(n => {
      if (!n.parentId) return false;
      if (view === 'trash') { if (!n.inTrash || trashRoots.has(n.id)) return false; if (!filterActive && !trashRoots.has(n.parentId)) return false; }
      else if (n.inTrash) return false;
      if (view === 'checks' && n.url === undefined) return false;
      if (view === 'library') {
        if (filterActive) { if (scope === 'current' && below && (!below.has(n.id) || n.id === folderId)) return false; }
        else if (folderId ? n.parentId !== folderId : n.url === undefined) return false;
      }
      if (search && !`${n.title}\n${n.url ?? ''}`.toLowerCase().includes(search)) return false;
      if (domain && !hostname(n.url).toLowerCase().includes(domain.toLowerCase())) return false;
      if (typeFilter === 'bookmark' && n.url === undefined || typeFilter === 'folder' && n.url !== undefined) return false;
      const r = results.get(n.id); const status = r?.stale ? 'stale' : r?.status ?? 'unchecked';
      return statusFilter === 'all' || status === statusFilter;
    });
  }, [records, folderId, view, search, scope, typeFilter, statusFilter, domain, results, state.metadata]);
  const navigate = (next: View, id?: string) => { setView(next); setFolderId(id); setSelected(new Set()); setQuery(''); setDomain(''); setStatusFilter('all'); setTypeFilter('all'); setScope(id ? 'current' : 'all'); };
  const run = async (work: () => Promise<unknown>, success?: string, close = true) => { setBusy(true); setError(''); try { await work(); if (close) setDialog(null); if (success) setToast(success); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } };
  const edit = (command: EditCommand, close = true) => run(async () => { const op = command.kind === 'import' ? await importTransfer(command.parentId, command.folderTitle, command.parsed) : await request<OperationRecord>({ type: 'edit', command }); setToast(`已提交：${op.label}。进度见“操作与版本”。`); setSelected(new Set()); }, undefined, close);
  const openDialog = (next: Dialog) => { setError(''); setDialog(next); setTargetId(folder && !folder.inTrash && !folder.readOnly ? folder.id : folders[0]?.id ?? ''); setDraftTitle(next === 'new-folder' ? '新建文件夹' : next === 'snapshot' ? '手动备份' : ''); setDraftUrl(''); setParsed(undefined); setSettings(state.settings); setCheckScope(selectedNodes.length ? 'selected' : folderId ? 'current' : 'all'); setPurgeAck(false); };
  const select = (n: BookmarkRecord, e: MouseEvent, checkbox = false) => {
    if (e.shiftKey && anchor.current) { const a = rows.findIndex(r => r.id === anchor.current); const b = rows.findIndex(r => r.id === n.id); if (a >= 0 && b >= 0) { setSelected(new Set([...(e.ctrlKey || e.metaKey ? selected : []), ...rows.slice(Math.min(a, b), Math.max(a, b) + 1).map(r => r.id)])); return; } }
    setSelected(prev => { if (checkbox || e.metaKey || e.ctrlKey) { const next = new Set(prev); if (next.has(n.id)) next.delete(n.id); else next.add(n.id); return next; } return new Set([n.id]); }); anchor.current = n.id;
  };
  const openNode = (n: BookmarkRecord) => { if (n.url === undefined) { if (n.inTrash) { setSelected(new Set([n.id])); setToast('请使用“恢复”保留目录结构；详情可查看原始位置。'); } else navigate('library', n.id); } else { try { if (!['http:', 'https:', 'ftp:', 'file:'].includes(new URL(n.url).protocol)) { setToast('请在详情中复制该地址到浏览器使用。'); return; } window.open(n.url, '_blank', 'noopener,noreferrer'); } catch { setError('URL 无效'); } } };
  const drop = (parentId: string, index?: number) => { const nodes = dragging.current.map(id => map.get(id)).filter(Boolean) as BookmarkRecord[]; dragging.current = []; if (!nodes.length) return; void edit({ kind: 'move', nodes: nodes.map(expected), parentId, index }); };
  const onDrag = (n: BookmarkRecord, e: DragEvent) => { const ids = selected.has(n.id) ? [...selected] : [n.id]; dragging.current = ids; e.dataTransfer.setData('application/x-bookmarker', JSON.stringify(ids)); e.dataTransfer.effectAllowed = 'move'; };
  const onDrop = (n: BookmarkRecord, e: DragEvent) => { e.preventDefault(); e.stopPropagation(); if (n.url === undefined) drop(n.id); else if (n.parentId && folderId === n.parentId && !search) { const draggedBefore = dragging.current.map(id => map.get(id)).filter(x => x && x.parentId === n.parentId && x.index < n.index).length; drop(n.parentId, Math.max(0, n.index - draggedBefore)); } };
  const scopeIds = (s: string) => { if (s === 'selected') return [...selectedDescendants]; if (s === 'current' && folderId) return [...descendants(folderId, records)]; if (s === 'retry') return ordinary.filter(n => { const r = results.get(n.id); return r && r.status !== 'ok'; }).map(n => n.id); return ordinary.map(n => n.id); };
  const startCheck = async () => {
    // This permission request is called directly from the user click (before other awaits).
    setError(''); setBusy(true);
    try { const granted = await chrome.permissions.request(CHECK_PERMISSIONS); await request({ type: 'check', nodeIds: scopeIds(checkScope), scope: ({ selected: '选中项目', current: '当前目录', all: '全部书签', retry: '失败项重测' })[checkScope] ?? checkScope }); setToast(granted ? '检测已开始；可以关闭管理页面，后台会保存进度。' : '未获得检测权限，任务会记录为已跳过；你仍可管理书签。'); setDialog(null); navigate('checks'); await refresh(); } catch (e) { setError(String(e instanceof Error ? e.message : e)); } finally { setBusy(false); }
  };
  const activeJob = state.jobs.find(j => ['queued', 'running'].includes(j.status));
  const runningOp = state.operations.find(o => ['queued', 'running', 'needs-review'].includes(o.status));
  const countOk = ordinary.filter(n => { const r = results.get(n.id); return r?.status === 'ok' && !r.stale; }).length;
  const countIssues = ordinary.filter(n => { const r = results.get(n.id); return r && !r.stale && !['ok', 'skipped'].includes(r.status); }).length;
  const breadcrumb = folder ? [...folder.path, folder.title] : [viewLabels[view]];

  return <div className="app-shell">
    <aside className="sidebar">
      <a className="brand" href="#" onClick={e => { e.preventDefault(); navigate('library'); }}><span className="brand-symbol"><Bookmark size={23} fill="currentColor"/></span><span>BookMarker<small>让收藏，井井有条</small></span></a>
      <div className="workspace-label">我的工作台 <span>LOCAL</span></div>
      <nav className="main-nav">
        {([['library', BookOpen, ordinary.length], ['checks', CheckCheck, countIssues || undefined], ['duplicates', Copy, groups.size || undefined]] as const).map(([key, Icon, count]) => <button key={key} className={view === key && !folderId ? 'active' : ''} onClick={() => navigate(key)}><Icon size={18}/><span>{viewLabels[key]}</span>{count !== undefined && <b>{count.toLocaleString()}</b>}</button>)}
      </nav>
      <div className="section-label">文件夹 <button className="icon-button" onClick={() => openDialog('new-folder')} aria-label="新建文件夹" disabled={!isExtension}><Plus size={15}/></button></div>
      <div className="tree-scroll"><FolderTree records={records} selected={folderId} onSelect={id => navigate('library', id)} onDrop={id => drop(id)}/>{!folders.length && <p className="sidebar-hint">浏览器中的文件夹<br/>会自动显示在这里</p>}</div>
      <nav className="bottom-nav"><button className={view === 'history' ? 'active' : ''} onClick={() => navigate('history')}><History size={18}/><span>操作与版本</span>{runningOp && <i className="sync-dot"/>}</button><button className={view === 'trash' ? 'active' : ''} onClick={() => navigate('trash')}><Trash2 size={18}/><span>回收站</span>{deleted.length > 0 && <b>{deleted.length}</b>}</button><button onClick={() => openDialog('settings')}><Settings2 size={18}/><span>设置</span></button></nav>
      <div className="local-card"><span><ShieldCheck size={18}/><strong>你的书签，只在本地</strong></span><p>无需账号 · 无需本机服务</p><button onClick={() => openDialog('help')}>了解数据与隐私 <ArrowUpRight size={13}/></button></div>
    </aside>
    <main className="main">
      <header className="topbar"><div className="workspace-title"><span className="green-dot"/>{isExtension ? '浏览器书签已连接' : '扩展安装预览'}<span className="topbar-divider"/><span className="subtle">本地工作空间</span></div><div><button onClick={() => openDialog('import')} disabled={!isExtension}><Upload size={16}/>导入</button><button onClick={() => openDialog('export')} disabled={!isExtension}><Download size={16}/>导出与备份</button><button className="icon-button" onClick={() => openDialog('help')} aria-label="帮助"><CircleHelp size={18}/></button></div></header>
      <div className="page-intro"><div><div className="eyebrow">YOUR PERSONAL LIBRARY</div><h1>{folder?.title || viewLabels[view]}<span>{view === 'library' ? '收藏有序，灵感随行。' : view === 'checks' ? '了解链接的当前状态。' : view === 'duplicates' ? '保留需要的每一份收藏。' : view === 'trash' ? '留一步，给改变主意。' : '每一次整理，都有迹可循。'}</span></h1></div><div className="intro-actions">{view === 'trash' ? <button className="danger" disabled={!deleted.length || busy} onClick={() => { setSelected(new Set(deleted.map(n => n.id))); openDialog('purge'); }}><Trash2 size={16}/>清空回收站</button> : view === 'history' ? <button className="primary" disabled={!isExtension} onClick={() => openDialog('snapshot')}><Archive size={16}/>创建快照</button> : <><button onClick={() => openDialog('check')} disabled={!ordinary.length || busy}><CheckCheck size={16}/>检测链接</button><button className="primary" onClick={() => openDialog('new-bookmark')} disabled={!isExtension || !folders.length}><Plus size={17}/>新建书签</button></>}</div></div>
      {!isExtension && <div className="install-banner"><Folder size={21}/><div><strong>准备好连接你的浏览器</strong><p>在 Chrome / Edge 的扩展管理页开启开发者模式，选择“加载已解压的扩展程序”并打开项目的 dist 文件夹。此预览页不会读写书签。</p></div></div>}
      {error && <div className="error-banner" role="alert"><span>{error}</span><button className="icon-button" aria-label="关闭错误" onClick={() => setError('')}><X size={16}/></button></div>}
      {view !== 'history' && view !== 'trash' && <div className="stats-grid"><Stat icon={<Bookmark size={19}/>} label="收藏的书签" value={ordinary.length} hint="与浏览器实时同步"/><Stat icon={<Folder size={19}/>} label="分类文件夹" value={records.filter(n => n.url === undefined && !n.fixed && !n.inTrash).length} hint="给每份灵感一个位置"/><Stat icon={<ShieldCheck size={19}/>} label="检测正常" value={countOk} hint="以最近一次检测为准" tone="green"/><Stat icon={<Link2 size={19}/>} label="需要留意" value={countIssues} hint="检测证据，仅供参考" tone="amber"/></div>}
      {activeJob && <div className="progress-strip"><LoaderCircle className="spin" size={17}/><span><strong>正在检测 · {activeJob.scope}</strong> {activeJob.items.filter(i => i.state === 'done').length} / {activeJob.items.length}</span><progress value={activeJob.items.filter(i => i.state === 'done').length} max={activeJob.items.length}/><button onClick={() => void run(() => request({ type: 'cancel-check', jobId: activeJob.id }), '已取消检测', false)}>取消</button></div>}
      {runningOp && <div className={`progress-strip ${runningOp.status === 'needs-review' ? 'attention' : ''}`}><History size={17}/><span>{runningOp.status === 'needs-review' ? '有操作需要核对' : runningOp.label} · {runningOp.steps.filter(s => s.state === 'done').length} / {runningOp.steps.length}</span><button onClick={() => navigate('history')}>查看进度 <ChevronRight size={14}/></button></div>}

      {view === 'history' ? <HistoryView state={state} run={run} edit={edit}/> : view === 'duplicates' ? <div className="duplicates-view"><Notice>仅按完整 URL 精确匹配，保留协议、参数和锚点。为每组选择保留项后，其余副本将移入各自来源区域的回收站。</Notice>{!groups.size ? <Empty title="没有重复的 URL" description="新的重复书签出现时，会显示在这里。"/> : [...groups].map(([url, nodes]) => <section className="duplicate-group" key={url}><header><span className="item-icon"><Copy size={18}/></span><div><strong>{nodes[0].title || '未命名书签'}</strong><span>{url}</span></div><b>{nodes.length} 份副本</b><button disabled={nodes.some(n => n.readOnly)} onClick={() => void edit({ kind: 'trash', nodes: nodes.filter(n => n.id !== (keepers[url] ?? nodes[0].id)).map(expected) }, false)}>保留所选，回收其余</button></header>{nodes.map(n => <label key={n.id} className="duplicate-item"><input type="radio" name={url} checked={(keepers[url] ?? nodes[0].id) === n.id} onChange={() => setKeepers(k => ({ ...k, [url]: n.id }))}/><strong>{n.title}</strong><span>{n.path.join(' / ')}</span><button onClick={e => { e.preventDefault(); navigate('library', n.parentId); setSelected(new Set([n.id])); }}>定位<ArrowUpRight size={13}/></button></label>)}</section>)}</div> : <div className="explorer">
        <section className="list-panel">
          <div className="list-topline"><div className="breadcrumbs"><button onClick={() => navigate('library')} aria-label="所有书签"><BookOpen size={15}/></button>{breadcrumb.map((s, i) => <span key={`${s}-${i}`}><ChevronRight size={12}/>{s}</span>)}</div><div className="list-count">{rows.length.toLocaleString()} 个项目<button className="icon-button" title="刷新" onClick={() => void refresh()}><RefreshCw size={15}/></button><button className="icon-button" aria-label={showDetails ? '收起详情' : '展开详情'} onClick={() => setShowDetails(x => !x)}>{showDetails ? <PanelRightClose size={16}/> : <PanelRightOpen size={16}/>}</button></div></div>
          <div className="search-row"><label className="search-input"><Search size={17}/><input placeholder="搜索书签名称或网址…" aria-label="搜索书签" value={query} onChange={e => setQuery(e.target.value)}/>{query && <button className="icon-button" aria-label="清除搜索" onClick={() => setQuery('')}><X size={14}/></button>}<kbd>⌘ K</kbd></label><select aria-label="搜索范围" value={scope} onChange={e => setScope(e.target.value)}><option value="all">全库</option><option value="current" disabled={!folderId}>当前目录</option></select></div>
          <div className="filter-row"><select aria-label="类型筛选" value={typeFilter} onChange={e => setTypeFilter(e.target.value)}><option value="all">所有类型</option><option value="bookmark">书签</option><option value="folder">文件夹</option></select><select aria-label="状态筛选" value={statusFilter} onChange={e => setStatusFilter(e.target.value)}><option value="all">全部状态</option>{Object.entries(STATUS_LABELS).map(([k, label]) => <option value={k} key={k}>{label}</option>)}</select><input className="domain-filter" placeholder="筛选域名" aria-label="域名筛选" value={domain} onChange={e => setDomain(e.target.value)}/><span className="filter-spacer"/><button className="text-button" title="在当前目录按名称排序，立即写入浏览器" disabled={!folderId || !!search || view !== 'library' || !!domain || statusFilter !== 'all' || typeFilter !== 'all' || rows.some(n => n.fixed || n.readOnly)} onClick={() => void edit({ kind: 'move', parentId: folderId!, index: 0, nodes: [...rows].sort((a, b) => a.title.localeCompare(b.title, 'zh-CN')).map(expected) }, false)}><ArrowUpDown size={14}/>名称排序</button></div>
          <div className="table-head"><div className="check-cell"><input type="checkbox" aria-label="全选当前列表" checked={rows.length > 0 && rows.every(n => selected.has(n.id))} onChange={e => setSelected(new Set(e.target.checked ? rows.map(n => n.id) : []))}/></div><span>名称</span><span className="domain-head">域名</span><span className="status-head">链接状态</span><span/></div>
          {loading ? <Empty title="正在读取书签" description="从当前浏览器配置读取数据…"/> : !rows.length ? <Empty title={query || domain || statusFilter !== 'all' ? '没有找到匹配项' : view === 'trash' ? '回收站是空的' : '给灵感一个位置'} description={query || domain || statusFilter !== 'all' ? '试试其他关键词，或调整筛选范围。' : view === 'trash' ? '移入回收站的书签可在这里恢复。' : '导入已有收藏，或者创建你的第一个书签。'}>{view === 'library' && isExtension && <button onClick={() => openDialog('import')}><Upload size={15}/>导入书签</button>}</Empty> : <VirtualList rows={rows} selected={selected} results={results} onSelect={select} onOpen={openNode} onContext={(n, e) => { e.preventDefault(); if (!selected.has(n.id)) setSelected(new Set([n.id])); setContext({ x: Math.min(e.clientX, window.innerWidth - 210), y: Math.min(e.clientY, window.innerHeight - 270), node: n }); }} onDrag={onDrag} onDrop={onDrop} showPath={!!search || !folderId || view === 'trash'}/>}
          <div className="list-footer"><span>{selectedNodes.length ? `已选择 ${selectedNodes.length} 项` : '点击查看详情，双击打开'}</span>{selectedNodes.length ? <div>{view === 'trash' ? <><button disabled={!mutable || busy} onClick={() => void edit({ kind: 'restore', nodes: selectedNodes.map(expected) })}><RotateCcw size={14}/>恢复</button><button className="text-danger" disabled={!mutable} onClick={() => openDialog('purge')}>永久删除</button></> : <><button disabled={!mutable} onClick={() => openDialog('rename')}><Pencil size={14}/>重命名</button><button disabled={!mutable} onClick={() => openDialog('move')}><FolderInput size={14}/>移动</button><button disabled={!mutable || busy} onClick={() => void edit({ kind: 'trash', nodes: selectedNodes.map(expected) })}><Trash2 size={14}/>回收</button></>}<button className="icon-button" aria-label="取消选择" onClick={() => setSelected(new Set())}><X size={14}/></button></div> : <span className="subtle">Cmd / Ctrl 多选 · Shift 连选</span>}</div>
        </section>
        {showDetails && <Details key={selectedNodes.map(n => n.id).join(',')} nodes={selectedNodes} results={results} metadata={state.metadata} edit={edit} busy={busy} onLocate={n => { navigate('library', n.parentId); setSelected(new Set([n.id])); }} onMove={() => openDialog('move')} onRename={() => openDialog('rename')}/>}
      </div>}
      <footer className="page-footer"><span><HardDrive size={13}/>所有修改即时保存到浏览器</span><span>BookMarker <b>1.0</b></span></footer>
    </main>
    {context && <div className="context-menu" style={{ left: context.x, top: context.y }}><button onClick={() => openNode(context.node)}><ArrowUpRight size={15}/>打开</button><button onClick={() => { navigate('library', context.node.parentId); setSelected(new Set([context.node.id])); }}><Folder size={15}/>定位到目录</button><hr/>{context.node.inTrash ? <><button disabled={!mutable} onClick={() => void edit({ kind: 'restore', nodes: selectedNodes.map(expected) })}><RotateCcw size={15}/>恢复</button><button disabled={!mutable} onClick={() => openDialog('purge')}><Trash2 size={15}/>永久删除…</button></> : <><button disabled={!mutable} onClick={() => openDialog('rename')}><Pencil size={15}/>重命名…</button><button disabled={!mutable} onClick={() => openDialog('move')}><FolderInput size={15}/>移动到…</button><button disabled={!mutable} onClick={() => void edit({ kind: 'trash', nodes: selectedNodes.map(expected) })}><Trash2 size={15}/>移入回收站</button></>}</div>}
    {toast && <div className="toast" role="status"><Check size={17}/><span>{toast}</span><button className="icon-button" onClick={() => setToast('')} aria-label="关闭提示"><X size={14}/></button></div>}
    {dialog && <Modal title={dialogTitles[dialog]} onClose={() => !busy && setDialog(null)} wide={['rename', 'import', 'help'].includes(dialog)}>
      {error && <div className="modal-error" role="alert">{error}</div>}
      {(dialog === 'new-bookmark' || dialog === 'new-folder') && <form onSubmit={e => { e.preventDefault(); void edit({ kind: 'create', parentId: targetId, title: draftTitle, ...(dialog === 'new-bookmark' ? { url: draftUrl } : {}) }); }}><label>名称<input autoFocus required value={draftTitle} onChange={e => setDraftTitle(e.target.value)} placeholder="给这份收藏起个名字"/></label>{dialog === 'new-bookmark' && <label>网址<input type="url" required value={draftUrl} onChange={e => setDraftUrl(e.target.value)} placeholder="https://"/></label>}<FolderSelect folders={folders} value={targetId} setValue={setTargetId}/><Notice>保存后立即写入当前浏览器。URL 以浏览器实际保存的值为准。</Notice><div className="modal-actions"><button type="button" onClick={() => setDialog(null)}>取消</button><button className="primary" disabled={busy || !targetId}>{busy ? '提交中…' : '创建'}</button></div></form>}
      {dialog === 'move' && <form onSubmit={e => { e.preventDefault(); void edit({ kind: 'move', nodes: selectedNodes.map(expected), parentId: targetId }); }}><p className="modal-lead">将选中的 {selectedNodes.length} 项移动到：</p><FolderSelect folders={folders.filter(n => !selectedDescendants.has(n.id))} value={targetId} setValue={setTargetId}/><div className="modal-actions"><button type="button" onClick={() => setDialog(null)}>取消</button><button className="primary" disabled={busy || !targetId}>移动</button></div></form>}
      {dialog === 'rename' && <form onSubmit={e => { e.preventDefault(); void edit({ kind: 'update', changes: renamePreview(selectedNodes, rename) }); }}><div className="form-grid"><label>查找文字<input value={rename.find} onChange={e => setRename({ ...rename, find: e.target.value })}/></label><label>替换为<input value={rename.replace} onChange={e => setRename({ ...rename, replace: e.target.value })}/></label><label>前缀<input value={rename.prefix} onChange={e => setRename({ ...rename, prefix: e.target.value })}/></label><label>后缀<input value={rename.suffix} onChange={e => setRename({ ...rename, suffix: e.target.value })}/></label></div><label className="checkbox-label"><input type="checkbox" checked={rename.numbering} onChange={e => setRename({ ...rename, numbering: e.target.checked })}/>添加连续编号<input aria-label="起始编号" className="number-input" type="number" value={rename.start} min={0} onChange={e => setRename({ ...rename, start: Number(e.target.value) })}/></label><div className="preview-table"><header><span>原名称</span><span>修改后预览</span></header>{renamePreview(selectedNodes, rename).map(c => <div key={c.expected.id}><span>{c.expected.title}</span><strong>{c.title || '（空标题）'}</strong></div>)}</div><div className="modal-actions"><span>共 {selectedNodes.length} 项 · 提交后立即生效</span><button className="primary" disabled={busy || !selectedNodes.length}>应用重命名</button></div></form>}
      {dialog === 'import' && <><label className="upload-zone"><Upload size={28}/><strong>{parsed ? parsed.source.name : '选择书签文件或项目备份'}</strong><span>HTML · Chromium Bookmarks · Firefox JSON · 项目 ZIP</span><input aria-label="导入文件" type="file" accept=".html,.htm,.json,.zip,application/json,text/html,application/zip" disabled={busy} onChange={e => { const f = e.target.files?.[0]; if (f) void run(async () => { const p = await parseFile(f.name, new Uint8Array(await f.arrayBuffer())); setParsed(p); setDraftTitle(`导入 · ${f.name.replace(/\.[^.]+$/, '')}`); }, undefined, false); }}/></label>{parsed && <><div className="import-summary"><span><strong>{importStats(parsed.nodes).bookmarks.toLocaleString()}</strong> 个书签</span><span><strong>{importStats(parsed.nodes).folders.toLocaleString()}</strong> 个目录</span><span>{parsed.format}</span></div><div className="import-tree">{parsed.nodes.slice(0, 30).map(n => <div key={n.key}>{n.url === undefined ? <Folder size={15}/> : <Globe size={15}/>}<span>{n.title || '未命名'}</span><small>{n.url ?? `${n.children?.length ?? 0} 个直接子项`}</small></div>)}{parsed.nodes.length > 30 && <small>另有 {parsed.nodes.length - 30} 个顶层项目</small>}</div><FolderSelect folders={folders} value={targetId} setValue={setTargetId}/><label>新建导入文件夹<input required value={draftTitle} onChange={e => setDraftTitle(e.target.value)}/></label><Notice>{parsed.warnings.map((w, i) => <p key={i}>{w}</p>)}<small className="hash">SHA-256 · {parsed.source.sha256}</small></Notice></>}<div className="modal-actions"><button onClick={() => setDialog(null)}>取消</button><button className="primary" disabled={busy || !parsed || !targetId || !draftTitle} onClick={() => parsed && void edit({ kind: 'import', parentId: targetId, folderTitle: draftTitle, parsed })}>{busy ? '解析中…' : '确认导入'}</button></div></>}
      {dialog === 'export' && <div className="export-options"><button onClick={() => { download(exportHtml(state.tree, state.metadata), `BookMarker-${new Date().toISOString().slice(0, 10)}.html`, 'text/html;charset=utf-8'); setToast('HTML 已生成，下载由浏览器处理'); setDialog(null); }}><Globe size={24}/><span><strong>通用书签 HTML</strong><small>UTF-8 · 可导入 Chrome / Edge / Firefox · 排除回收站</small></span><Download size={18}/></button><button disabled={busy} onClick={() => void run(async () => { const data = await backupTransfer(); download(encodeBackup(data), `BookMarker-project-${new Date().toISOString().slice(0, 10)}.zip`, 'application/zip'); }, '完整项目 ZIP 已生成')}><Archive size={24}/><span><strong>完整项目备份 ZIP</strong><small>书签、原文件、扩展元数据、历史、快照和检测结果</small></span>{busy ? <LoaderCircle className="spin" size={18}/> : <Download size={18}/>}</button><Notice>浏览器 API 未公开的元数据无法读取。卸载扩展会清除扩展内备份，下载的 ZIP 可以独立保留。</Notice></div>}
      {dialog === 'settings' && <form onSubmit={e => { e.preventDefault(); void run(() => request({ type: 'settings', settings }), '设置已保存'); }}><label className="checkbox-label"><input type="checkbox" checked={settings.allowPrivate} onChange={e => setSettings({ ...settings, allowPrivate: e.target.checked })}/>允许检测内网与本机地址</label><Notice>默认跳过明确的内网 IP、本机和已知内网域名。纯扩展无法提前识别所有域名的内网解析结果，此筛选不是严格的网络隔离。</Notice><div className="form-grid"><label>总并发（1–12）<input type="number" min={1} max={12} value={settings.concurrency} onChange={e => setSettings({ ...settings, concurrency: Number(e.target.value) })}/></label><label>同主机并发（1–2）<input type="number" min={1} max={2} value={settings.perHost} onChange={e => setSettings({ ...settings, perHost: Number(e.target.value) })}/></label></div><label>单次尝试超时（毫秒，最多 12000）<input type="number" min={1000} max={12000} step={1000} value={settings.timeoutMs} onChange={e => setSettings({ ...settings, timeoutMs: Number(e.target.value) })}/></label><Notice>请求使用浏览器适用的网络配置，不设置代理、不携带站点登录凭据，不使用云端数据库或 storage.sync。浏览器自身的书签同步由浏览器设置决定。</Notice><div className="modal-actions"><button type="button" onClick={() => setDialog(null)}>取消</button><button className="primary" disabled={busy || !isExtension}>保存设置</button></div></form>}
      {dialog === 'check' && <><p className="modal-lead">检测链接的当前响应，结果不会自动删除任何书签。</p><label>检测范围<select value={checkScope} onChange={e => setCheckScope(e.target.value)}><option value="selected" disabled={!selectedNodes.length}>选中项目（含子目录）</option><option value="current" disabled={!folderId}>当前目录（含子目录）</option><option value="all">全部书签</option><option value="retry">失败项重测</option></select></label><Notice>首次检测需要网站访问和 webRequest 权限。检测先发起 HEAD，必要时用 GET 复核，最多消费 64 KiB 正文；不携带登录凭据。站点会收到正常网络请求。</Notice><div className="check-facts"><span>并发 <b>{state.settings.concurrency}</b></span><span>同主机 <b>{state.settings.perHost}</b></span><span>单次超时 <b>{state.settings.timeoutMs / 1000}s</b></span><span>内网 <b>{state.settings.allowPrivate ? '允许' : '跳过'}</b></span></div><div className="modal-actions"><button onClick={() => setDialog(null)}>取消</button><button className="primary" disabled={busy || !scopeIds(checkScope).length} onClick={() => void startCheck()}>授权并开始检测</button></div></>}
      {dialog === 'purge' && <><Notice>将永久删除选中的 {selectedNodes.length} 个项目及其子目录。此操作不能通过移动恢复；即使重建，也无法保留原节点 ID、创建时间和未公开元数据。</Notice><label className="checkbox-label"><input type="checkbox" checked={purgeAck} onChange={e => setPurgeAck(e.target.checked)}/>我确认要永久删除这些内容</label><div className="modal-actions"><button onClick={() => setDialog(null)}>保留</button><button className="danger-fill" disabled={busy || !purgeAck || !mutable} onClick={() => void edit({ kind: 'purge', nodes: selectedNodes.map(expected), confirmed: true })}>永久删除</button></div></>}
      {dialog === 'snapshot' && <form onSubmit={e => { e.preventDefault(); void run(() => request({ type: 'snapshot', label: draftTitle }), '快照已创建'); }}><label>版本名称<input autoFocus required value={draftTitle} onChange={e => setDraftTitle(e.target.value)}/></label><Notice>快照保存在本机扩展内。回滚生成新版本，只撤回本工具能够确认的操作；外部修改会保留并显示冲突。</Notice><div className="modal-actions"><button className="primary" disabled={busy}>创建快照</button></div></form>}
      {dialog === 'help' && <div className="help-content"><h3>从浏览器开始，整理每一份收藏</h3><p>BookMarker 使用当前浏览器配置的书签。新建、编辑、移动和排序立即生效；浏览器和其他扩展的变更会同步到此页面。</p><div className="help-grid"><article><Folder size={21}/><h4>像管理文件一样</h4><p>双击打开，勾选或 Cmd/Ctrl 多选，Shift 连选。拖到文件夹移动；在当前目录中拖到书签上方排序。</p></article><article><Trash2 size={21}/><h4>先回收，再决定</h4><p>每个来源书签区域按需建立可见回收站。移动和恢复保留节点 ID，永久删除需要明确确认。</p></article><article><Archive size={21}/><h4>原件完整保留</h4><p>导入文件保存原始字节、SHA-256 和额外元数据。直接从浏览器读取时，仅能备份 API 开放的数据。</p></article><article><ShieldCheck size={21}/><h4>数据留在本地</h4><p>不上传书签、不使用云数据库。浏览器自身的书签同步仍由浏览器设置控制。下载 ZIP 可在卸载后继续保留。</p></article></div><Notice>连接异常和超时无法直接确定责任在本地网络或目标站点。错误原文仅作为证据；没有详情时显示“未提供详细错误”。浏览器关闭后检测停止，重新打开会续跑未完成任务。</Notice><p className="subtle">最低 Chromium 134 · 支持 Chrome 与 Edge · 第一版通过开发者模式加载</p></div>}
    </Modal>}
    <Shortcuts onSearch={() => document.querySelector<HTMLInputElement>('[aria-label="搜索书签"]')?.focus()} onDelete={() => { if (mutable && view !== 'trash' && !dialog) void edit({ kind: 'trash', nodes: selectedNodes.map(expected) }); }} onEscape={() => { setContext(undefined); if (!dialog) setSelected(new Set()); }}/>
  </div>;
}

const dialogTitles: Record<Exclude<Dialog, null>, string> = { 'new-bookmark': '新建书签', 'new-folder': '新建文件夹', move: '移动到文件夹', rename: '批量重命名', import: '导入与预览', export: '导出与备份', settings: '工作台设置', check: '检测网页可达性', purge: '永久删除确认', snapshot: '创建版本快照', help: '关于 BookMarker' };
function Stat({ icon, label, value, hint, tone = '' }: { icon: React.ReactNode; label: string; value: number; hint: string; tone?: string }) { return <div className={`stat-card ${tone}`}><div><span>{label}</span><i>{icon}</i></div><strong>{value.toLocaleString()}</strong><small>{hint}</small></div>; }
function FolderSelect({ folders, value, setValue }: { folders: BookmarkRecord[]; value: string; setValue: (id: string) => void }) { return <label>目标文件夹<select aria-label="目标文件夹" value={value} onChange={e => setValue(e.target.value)}><option value="" disabled>选择目录</option>{folders.map(n => <option key={n.id} value={n.id}>{[...n.path, n.title].join(' / ')}{n.syncing ? ' · 同步区域' : ''}</option>)}</select></label>; }
function Shortcuts({ onSearch, onDelete, onEscape }: { onSearch: () => void; onDelete: () => void; onEscape: () => void }) { useEffect(() => { const handler = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key === 'k') { e.preventDefault(); onSearch(); } if (e.key === 'Escape') onEscape(); if (e.key === 'Delete' && !['INPUT', 'TEXTAREA', 'SELECT'].includes((e.target as HTMLElement)?.tagName)) onDelete(); }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }); return null; }
function Details({ nodes, results, metadata, edit, busy, onLocate, onMove, onRename }: { nodes: BookmarkRecord[]; results: Map<string, CheckResult>; metadata: AppState['metadata']; edit: (c: EditCommand, close?: boolean) => Promise<void>; busy: boolean; onLocate: (n: BookmarkRecord) => void; onMove: () => void; onRename: () => void }) {
  const n = nodes[0]; const [title, setTitle] = useState(n?.title ?? ''); const [url, setUrl] = useState(n?.url ?? ''); const [copied, setCopied] = useState(false);
  const [base, setBase] = useState(n ? expected(n) : undefined);
  const dirty = !!n && (title !== base?.title || url !== (base?.url ?? ''));
  useEffect(() => { if (n && !dirty) { setTitle(n.title); setUrl(n.url ?? ''); setBase(expected(n)); } }, [n?.title, n?.url, n?.parentId, n?.index]);
  if (!nodes.length) return <aside className="details-panel"><div className="detail-heading">书签详情 <Ellipsis size={17}/></div><Empty title="看看收藏背后的细节" description="选择一个书签，查看网址、链接状态和保存信息。"/><div className="detail-tip"><Bookmark size={16}/><p>每一次整理，<br/>都是为了更轻松地找到。</p></div></aside>;
  if (nodes.length > 1) return <aside className="details-panel"><div className="detail-heading">批量管理</div><div className="multi-details"><span className="big-item-icon"><Copy size={29}/></span><h3>已选择 {nodes.length} 项</h3><p>支持移动、回收与批量重命名。</p><button onClick={onMove}>移动到文件夹</button><button onClick={onRename}>预览批量重命名</button></div></aside>;
  const r = results.get(n.id); const m = metadata.find(m => m.id === n.id); const writable = !n.fixed && !n.readOnly && !n.inTrash;
  return <aside className="details-panel"><div className="detail-heading">{n.url === undefined ? '文件夹详情' : '书签详情'}{n.readOnly || n.fixed ? <span className="subtle">只读</span> : <Pencil size={14}/>}</div><div className="detail-content"><div className="detail-hero"><span className="big-item-icon">{n.url === undefined ? <Folder size={29}/> : <Globe size={29}/>}</span><h3>{n.title || '未命名'}</h3><span>{n.url ? hostname(n.url) : `${n.children.length} 个直接子项`}</span></div>{n.url && <div className="detail-open"><SafeOpen url={n.url}/><button className="icon-button" aria-label="复制网址" onClick={() => { void navigator.clipboard.writeText(n.url!).then(() => { setCopied(true); setTimeout(() => setCopied(false), 1800); }); }}>{copied ? <Check size={16}/> : <Copy size={16}/>}</button></div>}<form onSubmit={e => { e.preventDefault(); if (base) void edit({ kind: 'update', changes: [{ expected: base, ...(title !== base.title ? { title } : {}), ...(url !== (base.url ?? '') ? { url } : {}) }] }, false); }}><label>名称<input aria-label="详情名称" disabled={!writable} value={title} onChange={e => setTitle(e.target.value)}/></label>{n.url !== undefined && <label>网址<textarea aria-label="详情网址" disabled={!writable} value={url} onChange={e => setUrl(e.target.value)} rows={3}/></label>}{writable && dirty && <button className="primary full-width" disabled={busy}>保存修改</button>}</form><div className="detail-section"><span className="field-label">所在文件夹</span><button className="path-button" onClick={() => onLocate(n)}><Folder size={14}/><span>{n.path.join(' / ')}</span><ArrowUpRight size={13}/></button><dl><dt>创建时间</dt><dd>{formatTime(n.dateAdded)}</dd><dt>节点 ID</dt><dd className="mono">{n.id}</dd><dt>存储区域</dt><dd>{n.syncing ? '浏览器账号同步' : '本地 / 浏览器管理'}</dd></dl></div>{n.url !== undefined && <div className="detail-section"><div className="section-title">链接状态 <Status result={r}/></div>{r ? <><dl><dt>检测时间</dt><dd>{formatTime(r.checkedAt)}</dd><dt>耗时</dt><dd>{r.durationMs} ms</dd>{r.httpStatus !== undefined && <><dt>HTTP 状态</dt><dd>{r.httpStatus} · {r.method}</dd></>}</dl>{r.finalUrl && <p className="detail-url">最终 URL<br/>{r.finalUrl}</p>}{r.reason && <p className="diagnostic">{r.reason}</p>}{r.rawError && <code className="raw-error">{r.rawError}</code>}{r.redirects.map((d, i) => <p className="detail-url" key={i}>{d.status} · {d.from} → {d.to}</p>)}</> : <p className="muted small">尚未检测。使用顶部“检测链接”查看当前响应。</p>}</div>}{m?.trash && <div className="detail-section"><span className="field-label">回收前位置</span><p className="small">目录 ID {m.trash.parentId} · 第 {m.trash.index + 1} 项</p><p className="small">{formatTime(m.trash.at)}</p></div>}{m && <details className="metadata-details"><summary>原始输入与来源元数据</summary>{m.originalInput && <p className="detail-url">{m.originalInput}</p>}<pre>{JSON.stringify(m, null, 2)}</pre></details>}</div></aside>;
}
function HistoryView({ state, run, edit }: { state: AppState; run: (work: () => Promise<unknown>, success?: string, close?: boolean) => Promise<void>; edit: (c: EditCommand, close?: boolean) => Promise<void> }) {
  const [tab, setTab] = useState('operations'); const [resolveIds, setResolveIds] = useState<Record<string, string>>({}); const [rollbackId, setRollbackId] = useState<string>();
  const labels: Record<string, string> = { queued: '等待执行', running: '正在执行', done: '已完成', partial: '部分完成', 'needs-review': '需要核对', cancelled: '已取消', pending: '等待执行', failed: '失败', conflict: '冲突', skipped: '已跳过' };
  return <section className="history-view"><div className="tabs"><button className={tab === 'operations' ? 'active' : ''} onClick={() => setTab('operations')}>操作记录 <b>{state.operations.length}</b></button><button className={tab === 'snapshots' ? 'active' : ''} onClick={() => setTab('snapshots')}>版本快照 <b>{state.snapshots.length}</b></button><button className={tab === 'checks' ? 'active' : ''} onClick={() => setTab('checks')}>检测任务 <b>{state.jobs.length}</b></button></div><Notice>每一步单独记录结果。批量操作可能部分完成；冲突不会覆盖外部修改。后台中断的新建操作需要核对后关联或跳过。自动保留最近 30 份每日快照，每 50 次操作及大型操作前另建快照。</Notice>
    {tab === 'operations' && (!state.operations.length ? <Empty title="还没有操作记录" description="从第一个书签开始，每次整理都会留下记录。"/> : state.operations.map(op => <details className="operation" key={op.id} open={op.status === 'needs-review' ? true : undefined}><summary><span className="operation-icon"><History size={18}/></span><div><strong>{op.label}</strong><small>{formatTime(op.createdAt)} · {op.steps.filter(s => s.state === 'done').length}/{op.steps.length} 项完成</small></div><span className={`operation-status ${op.status}`}>{labels[op.status]}</span></summary><div className="operation-body">{op.warnings.map((w, i) => <p className="diagnostic" key={i}>{w}</p>)}<div className="step-list">{op.steps.map(s => <div key={s.id} className="step"><span className={`step-dot ${s.state}`}/><div><strong>{s.after?.title ?? s.title ?? s.expected?.title ?? s.kind}</strong><small>{s.kind} · {labels[s.state]}{s.error && ` · ${s.error}`}</small>{s.state === 'needs-review' && <div className="resolve-row"><input placeholder="核对后的浏览器节点 ID" aria-label="关联节点 ID" value={resolveIds[s.id] ?? ''} onChange={e => setResolveIds(ids => ({ ...ids, [s.id]: e.target.value }))}/><button disabled={!resolveIds[s.id]} onClick={() => void run(() => request({ type: 'resolve', operationId: op.id, stepId: s.id, action: 'adopt', nodeId: resolveIds[s.id] }), '节点已关联', false)}>关联此节点</button><button onClick={() => void run(() => request({ type: 'resolve', operationId: op.id, stepId: s.id, action: 'skip' }), '已跳过，不会自动重建', false)}>核对后跳过</button></div>}</div></div>)}</div><div className="operation-actions">{['done', 'partial'].includes(op.status) && <>{op.undoOf ? <button disabled={state.operations.some(o => o.redoOf === op.id)} onClick={() => void edit({ kind: 'redo', operationId: op.id }, false)}><RefreshCw size={14}/>重做</button> : <button disabled={state.operations.some(o => o.undoOf === op.id)} onClick={() => void edit({ kind: 'undo', operationId: op.id }, false)}><RotateCcw size={14}/>撤销已完成项</button>}</>}</div></div></details>))}
    {tab === 'snapshots' && state.snapshots.map(s => <div className="snapshot-row" key={s.id}><span className="operation-icon"><Archive size={18}/></span><div><strong>{s.label}</strong><small>{formatTime(s.createdAt)} · {s.kind === 'daily' ? '每日备份' : s.kind === 'automatic' ? '自动快照' : '手动快照'}</small></div><button onClick={() => setRollbackId(s.id)}><RotateCcw size={14}/>回滚预览</button></div>)}
    {tab === 'checks' && (!state.jobs.length ? <Empty title="没有检测任务" description="从顶部“检测链接”开始检查收藏。"/> : state.jobs.map(j => <details className="operation" key={j.id}><summary><span className="operation-icon"><CheckCheck size={18}/></span><div><strong>{j.scope}</strong><small>{formatTime(j.createdAt)} · {j.items.filter(i => i.state === 'done').length}/{j.items.length} 项</small></div><span className="operation-status">{labels[j.status]}</span></summary><div className="step-list check-history">{state.results.filter(r => r.jobId === j.id).map(r => <div key={r.id}><Status result={r}/><span>{r.url}</span><small>{r.httpStatus ?? r.rawError ?? r.reason}</small></div>)}</div></details>))}
    {rollbackId && <Modal title="回滚预览" onClose={() => setRollbackId(undefined)}><Notice>将逆序撤回选中快照之后本工具的操作，生成新的操作版本。外部变更不会被强行覆盖；永久删除不能恢复原 ID。请先下载项目 ZIP 保留独立备份。</Notice><div className="rollback-preview">{state.operations.filter(o => o.createdAt > state.snapshots.find(s => s.id === rollbackId)!.createdAt).map(o => <p key={o.id}>{o.label} · {labels[o.status]}</p>)}</div><div className="modal-actions"><button onClick={() => setRollbackId(undefined)}>取消</button><button className="primary" onClick={() => { void edit({ kind: 'rollback', snapshotId: rollbackId }, false); setRollbackId(undefined); }}>确认回滚</button></div></Modal>}
  </section>;
}
