import { useEffect, useState } from 'react';
import { Ellipsis, Copy, Pencil, Folder, Globe, Check, ArrowUpRight } from 'lucide-react';
import { expected, hostname } from '../tree';
import type { AppState, BookmarkRecord, CheckResult, EditCommand } from '../types';
import { Empty, formatTime, SafeOpen, Status } from './components';

export function Details({ nodes, results, metadata, edit, busy, onLocate, onMove, onRename }: { nodes: BookmarkRecord[]; results: Map<string, CheckResult>; metadata: AppState['metadata']; edit: (c: EditCommand, close?: boolean) => Promise<void>; busy: boolean; onLocate: (n: BookmarkRecord) => void; onMove: () => void; onRename: () => void }) {
  const n = nodes[0]; const [title, setTitle] = useState(n?.title ?? ''); const [url, setUrl] = useState(n?.url ?? ''); const [copied, setCopied] = useState(false);
  const [base, setBase] = useState(n ? expected(n) : undefined);
  const dirty = !!n && (title !== base?.title || url !== (base?.url ?? ''));
  useEffect(() => { if (n && (!dirty || (title === n.title && url === (n.url ?? '')))) { setTitle(n.title); setUrl(n.url ?? ''); setBase(expected(n)); } }, [n?.title, n?.url, n?.parentId, n?.index]);
  if (!nodes.length) return <aside className="details-panel"><div className="detail-heading">书签详情 <Ellipsis size={17}/></div><Empty title="未选择项目" description="选择项目以查看和编辑属性。"/></aside>;
  if (nodes.length > 1) return <aside className="details-panel"><div className="detail-heading">批量管理</div><div className="multi-details"><span className="big-item-icon"><Copy size={29}/></span><h3>已选择 {nodes.length} 项</h3><p>支持移动、回收与批量重命名。</p><button onClick={onMove}>移动到文件夹</button><button onClick={onRename}>预览批量重命名</button></div></aside>;
  const r = results.get(n.id); const m = metadata.find(m => m.id === n.id); const writable = !n.fixed && !n.readOnly && !n.inTrash;
  return <aside className="details-panel"><div className="detail-heading">{n.url === undefined ? '文件夹详情' : '书签详情'}{n.readOnly || n.fixed ? <span className="subtle">只读</span> : <Pencil size={14}/>}</div><div className="detail-content"><div className="detail-hero"><span className="big-item-icon">{n.url === undefined ? <Folder size={29}/> : <Globe size={29}/>}</span><h3>{n.title || '未命名'}</h3><span>{n.url ? hostname(n.url) : `${n.children.length} 个直接子项`}</span></div>{n.url && <div className="detail-open"><SafeOpen url={n.url}/><button className="icon-button" aria-label="复制网址" onClick={() => { void navigator.clipboard.writeText(n.url!).then(() => { setCopied(true); setTimeout(() => setCopied(false), 1800); }); }}>{copied ? <Check size={16}/> : <Copy size={16}/>}</button></div>}<form onSubmit={e => { e.preventDefault(); if (base) void edit({ kind: 'update', changes: [{ expected: base, ...(title !== base.title ? { title } : {}), ...(url !== (base.url ?? '') ? { url } : {}) }] }, false); }}><label>名称<input aria-label="详情名称" disabled={!writable} value={title} onChange={e => setTitle(e.target.value)}/></label>{n.url !== undefined && <label>网址<textarea aria-label="详情网址" disabled={!writable} value={url} onChange={e => setUrl(e.target.value)} rows={3}/></label>}{writable && dirty && <button className="primary full-width" disabled={busy}>保存修改</button>}</form><div className="detail-section"><span className="field-label">所在文件夹</span><button className="path-button" onClick={() => onLocate(n)}><Folder size={14}/><span>{n.path.join(' / ')}</span><ArrowUpRight size={13}/></button><dl><dt>创建时间</dt><dd>{formatTime(n.dateAdded)}</dd><dt>节点 ID</dt><dd className="mono">{n.id}</dd><dt>存储区域</dt><dd>{n.syncing ? '浏览器账号同步' : '本地 / 浏览器管理'}</dd></dl></div>{n.url !== undefined && <div className="detail-section"><div className="section-title">链接状态 <Status result={r}/></div>{r ? <><dl><dt>检测时间</dt><dd>{formatTime(r.checkedAt)}</dd><dt>耗时</dt><dd>{r.durationMs} ms</dd>{r.httpStatus !== undefined && <><dt>HTTP 状态</dt><dd>{r.httpStatus} · {r.method}</dd></>}</dl>{r.finalUrl && <p className="detail-url">最终 URL<br/>{r.finalUrl}</p>}{r.reason && <p className="diagnostic">{r.reason}</p>}{r.rawError && <code className="raw-error">{r.rawError}</code>}{r.redirects.map((d, i) => <p className="detail-url" key={i}>{d.status} · {d.from} → {d.to}</p>)}</> : <p className="muted small">尚未检测。使用顶部“检测链接”查看当前响应。</p>}</div>}{m?.trash && <div className="detail-section"><span className="field-label">回收前位置</span><p className="small">目录 ID {m.trash.parentId} · 第 {m.trash.index + 1} 项</p><p className="small">{formatTime(m.trash.at)}</p></div>}{m && <details className="metadata-details"><summary>原始输入与来源元数据</summary>{m.originalInput && <p className="detail-url">{m.originalInput}</p>}<pre>{JSON.stringify(m, null, 2)}</pre></details>}</div></aside>;
}
