import { useState } from 'react';
import { History, CheckCheck, RefreshCw, RotateCcw, Archive } from 'lucide-react';
import { request } from '../client';
import type { AppState, EditCommand } from '../types';
import { Empty, formatTime, Modal, Notice, Status } from './components';

export function HistoryView({ state, run, edit }: { state: AppState; run: (work: () => Promise<unknown>, success?: string, close?: boolean) => Promise<void>; edit: (c: EditCommand, close?: boolean) => Promise<void> }) {
  const [tab, setTab] = useState('operations'); const [resolveIds, setResolveIds] = useState<Record<string, string>>({}); const [rollbackId, setRollbackId] = useState<string>();
  const labels: Record<string, string> = { queued: '等待执行', running: '正在执行', done: '已完成', partial: '部分完成', 'needs-review': '需要核对', cancelled: '已取消', pending: '等待执行', failed: '失败', conflict: '冲突', skipped: '已跳过' };
  return <section className="history-view"><div className="tabs"><button className={tab === 'operations' ? 'active' : ''} onClick={() => setTab('operations')}>操作记录 <b>{state.operations.length}</b></button><button className={tab === 'snapshots' ? 'active' : ''} onClick={() => setTab('snapshots')}>版本快照 <b>{state.snapshots.length}</b></button><button className={tab === 'checks' ? 'active' : ''} onClick={() => setTab('checks')}>检测任务 <b>{state.jobs.length}</b></button></div><Notice>每一步单独记录结果。批量操作可能部分完成；冲突不会覆盖外部修改。后台中断的新建操作需要核对后关联或跳过。自动保留最近 30 份每日快照，每 50 次操作及大型操作前另建快照。</Notice>
    {tab === 'operations' && (!state.operations.length ? <Empty title="还没有操作记录" description="从第一个书签开始，每次整理都会留下记录。"/> : state.operations.map(op => <details className="operation" key={op.id} open={op.status === 'needs-review' ? true : undefined}><summary><span className="operation-icon"><History size={18}/></span><div><strong>{op.label}</strong><small>{formatTime(op.createdAt)} · {op.steps.filter(s => s.state === 'done').length}/{op.steps.length} 项完成</small></div><span className={`operation-status ${op.status}`}>{labels[op.status]}</span></summary><div className="operation-body">{op.warnings.map((w, i) => <p className="diagnostic" key={i}>{w}</p>)}<div className="step-list">{op.steps.map(s => <div key={s.id} className="step"><span className={`step-dot ${s.state}`}/><div><strong>{s.after?.title ?? s.title ?? s.expected?.title ?? s.kind}</strong><small>{s.kind} · {labels[s.state]}{s.error && ` · ${s.error}`}</small>{s.state === 'needs-review' && <div className="resolve-row"><input placeholder="核对后的浏览器节点 ID" aria-label="关联节点 ID" value={resolveIds[s.id] ?? ''} onChange={e => setResolveIds(ids => ({ ...ids, [s.id]: e.target.value }))}/><button disabled={!resolveIds[s.id]} onClick={() => void run(() => request({ type: 'resolve', operationId: op.id, stepId: s.id, action: 'adopt', nodeId: resolveIds[s.id] }), '节点已关联', false)}>关联此节点</button><button onClick={() => void run(() => request({ type: 'resolve', operationId: op.id, stepId: s.id, action: 'skip' }), '已跳过，不会自动重建', false)}>核对后跳过</button></div>}</div></div>)}</div><div className="operation-actions">{['done', 'partial'].includes(op.status) && <>{op.undoOf ? <button disabled={state.operations.some(o => o.redoOf === op.id)} onClick={() => void edit({ kind: 'redo', operationId: op.id }, false)}><RefreshCw size={14}/>重做</button> : <button disabled={state.operations.some(o => o.undoOf === op.id)} onClick={() => void edit({ kind: 'undo', operationId: op.id }, false)}><RotateCcw size={14}/>撤销已完成项</button>}</>}</div></div></details>))}
    {tab === 'snapshots' && state.snapshots.map(s => <div className="snapshot-row" key={s.id}><span className="operation-icon"><Archive size={18}/></span><div><strong>{s.label}</strong><small>{formatTime(s.createdAt)} · {s.kind === 'daily' ? '每日备份' : s.kind === 'automatic' ? '自动快照' : '手动快照'}</small></div><button onClick={() => setRollbackId(s.id)}><RotateCcw size={14}/>回滚预览</button></div>)}
    {tab === 'checks' && (!state.jobs.length ? <Empty title="没有检测任务" description="从顶部“检测链接”开始检查收藏。"/> : state.jobs.map(j => <details className="operation" key={j.id}><summary><span className="operation-icon"><CheckCheck size={18}/></span><div><strong>{j.scope}</strong><small>{formatTime(j.createdAt)} · {j.items.filter(i => i.state === 'done').length}/{j.items.length} 项</small></div><span className="operation-status">{labels[j.status]}</span></summary><div className="step-list check-history">{state.results.filter(r => r.jobId === j.id).map(r => <div key={r.id}><Status result={r}/><span>{r.url}</span><small>{r.httpStatus ?? r.rawError ?? r.reason}</small></div>)}</div></details>))}
    {rollbackId && <Modal title="回滚预览" onClose={() => setRollbackId(undefined)}><Notice>将逆序撤回选中快照之后本工具的操作，生成新的操作版本。外部变更不会被强行覆盖；永久删除不能恢复原 ID。请先下载项目 ZIP 保留独立备份。</Notice><div className="rollback-preview">{state.operations.filter(o => o.createdAt > state.snapshots.find(s => s.id === rollbackId)!.createdAt).map(o => <p key={o.id}>{o.label} · {labels[o.status]}</p>)}</div><div className="modal-actions"><button onClick={() => setRollbackId(undefined)}>取消</button><button className="primary" onClick={() => { void edit({ kind: 'rollback', snapshotId: rollbackId }, false); setRollbackId(undefined); }}>确认回滚</button></div></Modal>}
  </section>;
}
